name: Botswana_Housing_Corporation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  file_picker: ^8.0.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  awesome_dialog: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bhc_logo.png
    - assets/1.jpg
    - assets/user.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bhc_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/bhc_icon.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/bhc_logo.jpg
  android: true
  ios: true
  web: true
  android_gravity: fill
  ios_content_mode: scaleAspectFit
  fullscreen: true
